server:
  port: 8080
  servlet:
    #项目访问路径
    context-path: /starboot
jasypt:
  encryptor:
    password: 123456

starboot:
  file:
    root: '/startboot/'
    starboot-version: 'v1.0.0'

spring:
  profiles:
    active: dev

